### PR TITLE
Fixed 'str' object has no attribute 'value' error in Python 2.7

### PR DESCRIPTION
**Pull request by Tyzer34**
Thank you for the acknowledgement! FYI, I am working on Python 2.7.
I upgraded the libsoundtouch library to the new 0.2.0 version, but I was getting the error as stated above. This is caused by the Enum types chosen (and is very strange that this error did not pop up before).
I removed the ".value" statement after calling upon the Enum values, which fixed the problem (hence this pull request).

### CODE REVIEW

**Comment by Tyzer34** [comment]
To answer one of your previous questions @CharlesBlonde: "Because you are sending Key.PAUSE for example instead of PAUSE in each HTTP request."
The actual send requests will send over PAUSE instead of Key.PAUSE, even though the test shows that Key.PAUSE is received. This is why this test has failed again.
Did you have issues regarding this because you are using a Python 3 version?
With Python 2.7, this build works.

**Comment by CharlesBlonde** [comment]
Ok, I think I found the problem: you added a new dependency (enum34) but I forgot to add it in the release.
As it is a Python 3.4 backport, it had no impact in Python 3.4. That's why I was not able to see the problem and the Python 2.7 unit tests was working fine because dependencies are managed by requirements.txt file who was up to date.

I was able to reproduce the problem you had with the 0.2.0 version and I released a new 0.2.1 version.

Can you confirm it is now working for you ?

Besides, doing this tests I discover a new bug only on Python 2.7 if the status description contains non ASCII characters (in XML). I'll create an issue and fix it in the coming days.

**Comment by Tyzer34** [comment]
I'm very happy to see it working over here! Thank you :)
